FROM debian:stable-20260112-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
              git \
              build-essential \  
              python3 \
              python3-pip \
              iproute2 \  
              iptables \
              tcpdump \
        && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=

RUN git clone -b v1.6 https://github.com/mz-automation/libiec61850.git /tmp/libiec61850

RUN cd /tmp/libiec61850 && make dynlib \
	&&  cp build/libiec61850.so /usr/local/lib/

RUN git clone -b master https://github.com/mz-automation/lib60870.git /tmp/lib60870

RUN cd /tmp/lib60870/lib60870-C && make dynlib \
	&&  cp build/liblib60870.so /usr/local/lib/libiec60870.so

COPY ./requirements.txt /srv/iec61850_open_client/requirements.txt

RUN cd /srv/iec61850_open_client && pip3 install --break-system-packages -r requirements.txt 

COPY . /srv/iec61850_open_client

WORKDIR /srv/iec61850_open_client


# --- ДОБАВЛЯЕМ BEELZEBUB ---
# Копируем сертификаты, бинарник и конфиги напрямую из вашего образа custom-beelzebub
COPY --from=custom-beelzebub /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=custom-beelzebub /opt/beelzebub /opt/beelzebub

# Копируем и настраиваем стартовый скрипт
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Добавляем порты Beelzebub к портам клиента
EXPOSE 22 80 2222 8080

# Используем наш скрипт как точку входа
ENTRYPOINT ["/entrypoint.sh"]


EXPOSE 5000

CMD ["python3","app.py","-nD"]

